### ISSUE TITLE
Expand Metrichor call

### ISSUE THREAD

**Issue by trvrb** [blab/zika-seq#2]
@alliblk ---

Could you expand on the command line argument you ran to get raw reads basecalled with Metrichor? Right now I just have `metrichor-cli`:

https://github.com/blab/zika-seq/blob/master/README.md#base-calling

**Comment by barneypotter24** [comment]
Since Metrichor is no longer available, can this issue be closed?

**Comment by alliblk** [comment]
Closing issue due to deprecation of Metrichor by ONT. All basecalling is now performed by Albacore.
